# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: super-linter/super-linter:latest
        env:
          VALIDATE_CPP: true
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true
          CPP_CLANG_FORMAT_CONFIG_FILE: .clang-format
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
